# ======================================================================
# 19 Jekyll yapılandırması
# ======================================================================

# kalıcı adresler (lütfen bu ayara dokunmayın)
permalink: /:categories:month/:title

# sözdizimi renklendirmesi
pygments: true

# tırnak karakterlerinin daha şık çıkması için smartypants
rdiscount:
  extensions: [smart]

# ----------------------------------------------------------------------
# temel parametreler
# 
# bu parameterleri doğrudan "site" uzayına yerleştiriyoruz
# ----------------------------------------------------------------------

# github hesap adı (ör. roktas)
account:tugdev

# github organizasyonu (ör. 19)
organization: 19

# bu siteyi üreten github deposu (ör. roktas.github.com)
# dikkat!  depo çoğunlukla <account>.github.com formundadır.  fakat başka
# bir depo da olabilir.  url parametresi için yazılan açıklamayı okuyun.
repository: tugdev.github.com 

# üretilen sitenin web adresi ne?  ör. "http://roktas.github.com".
# CNAME kaydımız varsa bu adresi giriyoruz.  dikkat!  bu site
# <account>.github.com altına konumlandırmak istediğimiz bir site
# örneğin http://roktas.github.com/test olabilir.  fakat bu durumda
# kurulumdan sonra "master" dalını "gh-pages" dalına birleştirmelisiniz.
# 	git checkout -b gh-pages
url: http://tugdev.github.com

# site görünümüne ilişkin olarak sitede mutlak adres yoluyla herhangi bir
# sayfadan erişilebilecek ortak "dijital varlıklar"ın (ör. logolar) adresi.
# dikkat!  bu adres tercihen bir url olmalıdır.  aksi halde ilgili
# görselin erişilebilir olması tamamen o sayfanın bulunduğu yere bağlıdır.
#
# site görünümüne ait görsel ve javascript dosyaları chrome dizininde
# olduğuna göre bu parametre için örnek bir değer:
#   
# 	http://roktas.github.com/chrome
assets: http://tugdev.github.com/chrome

# ----------------------------------------------------------------------
# site parametreleri
# 
# kalan tüm parameterleri "site.param" uzayına koyuyoruz
# ----------------------------------------------------------------------
param:
        # --------------------------------------------------------------
        # kişisel parametreler
        # --------------------------------------------------------------
        # unix kullanıcı adı (ör. roktas)
        # dikkat!  unix kullanıcı adı github hesabından farklı olabilir
        user:tugdev
        # tam kullanıcı adı (ör. roktas)
        fullname: Tugba Devravut
        # email adresi (ör. roktas@bil.omu.edu.tr)
        email:  tugba.devravut@bil.omu.edu.tr
        # ünvan (ör. Bilgisayar Mühendisliği Öğrencisi)
        title:  Bilgisayar Mühendisliği Öğrencisi
        # GnuPG kısa parmak izi (ör. DEADBEEF)
        gpg: ~
        # twitter adresi (ör. http://19.status.net/roktas)
        twitter: https://twitter.com/xtugdevx
        # flick adresi (ör. http://flickr.com/photos/roktas)
        flickr: 
        # facebook adresi (ör. http://facebook.com/roktas)
        facebook:  http://facebook.com/TugBadvRvt
        # özet akışı adresi (ör. http://feeds.feedburner.com/roktas)
        feed: ~

        # --------------------------------------------------------------
        # sitede kullanılan bazı metinler
        # --------------------------------------------------------------
        section0: Web Günlüğü
        section1: Makaleler
        section2: İlkeler
        section7: Çeşitli
        section9: Notlar

        # --------------------------------------------------------------
        # ekstra özellik parametreleri
        #
        # bu değişkenler tanımlanmazsa (~ kullanın) öntanımlı sitede
        # ilgili özellik bulunmayacaktır (örneğin: disqus)
        #
        # dikkat!  değişkenin tanımlı olmaması için ~ değeri verin
        # --------------------------------------------------------------
        # girdi arşivi
        archive: Son Girdiler
        # ilişkili girdiler
        related: Diğer Girdiler
        # logo (ör. http://00010011.github.com/assets/19/19-normal-128x128.png)
        logo: /chrome/19/logo.png
        # google site içi arama kutusu
        google: ~
        # google analytics takip numarası (ör. UA-1234567-8
        googleanalyticsid: 
        # sayfa yorumları için disqus site kaydı (ör. roktas)
        disqus: tugdev
        # GitHub şerit metni (ör. GitHub'dayım)
        ribbon: GitHub'dayım
